// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcProtocol.proto

package com.zyd.common.proto.client;

public final class RpcProtocol {
  private RpcProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.zyd.common.proto.client.RpcType}
   */
  public enum RpcType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RPC_REQUEST = 0;</code>
     */
    RPC_REQUEST(0, 0),
    /**
     * <code>RPC_RESPONSE = 1;</code>
     */
    RPC_RESPONSE(1, 1),
    /**
     * <code>RPC_CANCEL = 2;</code>
     */
    RPC_CANCEL(2, 2),
    /**
     * <code>RPC_TRANSMIT = 3;</code>
     */
    RPC_TRANSMIT(3, 3),
    /**
     * <code>RPC_TRANSMIT_RESPONSE_VALUE = 4;</code>
     */
    RPC_TRANSMIT_RESPONSE_VALUE(4, 4),
    /**
     * <code>RPC_PUSH_TO_CLIENT = 5;</code>
     */
    RPC_PUSH_TO_CLIENT(5, 5),
    /**
     * <code>RPC_PROXY_BROAD_CAST = 6;</code>
     */
    RPC_PROXY_BROAD_CAST(6, 6),
    /**
     * <code>RPC_SERVER_HEART_BEAT_REQUEST = 7;</code>
     */
    RPC_SERVER_HEART_BEAT_REQUEST(7, 7),
    /**
     * <code>RPC_SERVER_HEART_BEAT_RESPONSE = 8;</code>
     */
    RPC_SERVER_HEART_BEAT_RESPONSE(8, 8),
    ;

    /**
     * <code>RPC_REQUEST = 0;</code>
     */
    public static final int RPC_REQUEST_VALUE = 0;
    /**
     * <code>RPC_RESPONSE = 1;</code>
     */
    public static final int RPC_RESPONSE_VALUE = 1;
    /**
     * <code>RPC_CANCEL = 2;</code>
     */
    public static final int RPC_CANCEL_VALUE = 2;
    /**
     * <code>RPC_TRANSMIT = 3;</code>
     */
    public static final int RPC_TRANSMIT_VALUE = 3;
    /**
     * <code>RPC_TRANSMIT_RESPONSE_VALUE = 4;</code>
     */
    public static final int RPC_TRANSMIT_RESPONSE_VALUE_VALUE = 4;
    /**
     * <code>RPC_PUSH_TO_CLIENT = 5;</code>
     */
    public static final int RPC_PUSH_TO_CLIENT_VALUE = 5;
    /**
     * <code>RPC_PROXY_BROAD_CAST = 6;</code>
     */
    public static final int RPC_PROXY_BROAD_CAST_VALUE = 6;
    /**
     * <code>RPC_SERVER_HEART_BEAT_REQUEST = 7;</code>
     */
    public static final int RPC_SERVER_HEART_BEAT_REQUEST_VALUE = 7;
    /**
     * <code>RPC_SERVER_HEART_BEAT_RESPONSE = 8;</code>
     */
    public static final int RPC_SERVER_HEART_BEAT_RESPONSE_VALUE = 8;


    public final int getNumber() { return value; }

    public static RpcType valueOf(int value) {
      switch (value) {
        case 0: return RPC_REQUEST;
        case 1: return RPC_RESPONSE;
        case 2: return RPC_CANCEL;
        case 3: return RPC_TRANSMIT;
        case 4: return RPC_TRANSMIT_RESPONSE_VALUE;
        case 5: return RPC_PUSH_TO_CLIENT;
        case 6: return RPC_PROXY_BROAD_CAST;
        case 7: return RPC_SERVER_HEART_BEAT_REQUEST;
        case 8: return RPC_SERVER_HEART_BEAT_RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RpcType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RpcType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RpcType>() {
            public RpcType findValueByNumber(int number) {
              return RpcType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zyd.common.proto.client.RpcProtocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final RpcType[] VALUES = values();

    public static RpcType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private RpcType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.zyd.common.proto.client.RpcType)
  }

  /**
   * Protobuf enum {@code com.zyd.common.proto.client.RPCQueueIDEnum}
   */
  public enum RPCQueueIDEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN_QUEUE = 1;</code>
     */
    LOGIN_QUEUE(0, 1),
    /**
     * <code>ROOM_GAME_QUEUE = 2;</code>
     */
    ROOM_GAME_QUEUE(1, 2),
    /**
     * <code>THIRD_QUEUE = 3;</code>
     */
    THIRD_QUEUE(2, 3),
    /**
     * <code>MAIN_QUEUE = 4;</code>
     */
    MAIN_QUEUE(3, 4),
    ;

    /**
     * <code>LOGIN_QUEUE = 1;</code>
     */
    public static final int LOGIN_QUEUE_VALUE = 1;
    /**
     * <code>ROOM_GAME_QUEUE = 2;</code>
     */
    public static final int ROOM_GAME_QUEUE_VALUE = 2;
    /**
     * <code>THIRD_QUEUE = 3;</code>
     */
    public static final int THIRD_QUEUE_VALUE = 3;
    /**
     * <code>MAIN_QUEUE = 4;</code>
     */
    public static final int MAIN_QUEUE_VALUE = 4;


    public final int getNumber() { return value; }

    public static RPCQueueIDEnum valueOf(int value) {
      switch (value) {
        case 1: return LOGIN_QUEUE;
        case 2: return ROOM_GAME_QUEUE;
        case 3: return THIRD_QUEUE;
        case 4: return MAIN_QUEUE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RPCQueueIDEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RPCQueueIDEnum>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RPCQueueIDEnum>() {
            public RPCQueueIDEnum findValueByNumber(int number) {
              return RPCQueueIDEnum.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zyd.common.proto.client.RpcProtocol.getDescriptor().getEnumTypes().get(1);
    }

    private static final RPCQueueIDEnum[] VALUES = values();

    public static RPCQueueIDEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private RPCQueueIDEnum(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.zyd.common.proto.client.RPCQueueIDEnum)
  }

  public interface RpcHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.zyd.common.proto.client.RpcType type = 1;
    /**
     * <code>required .com.zyd.common.proto.client.RpcType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.zyd.common.proto.client.RpcType type = 1;</code>
     */
    com.zyd.common.proto.client.RpcProtocol.RpcType getType();

    // required uint32 id = 2;
    /**
     * <code>required uint32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 2;</code>
     */
    int getId();

    // optional uint32 error = 3;
    /**
     * <code>optional uint32 error = 3;</code>
     */
    boolean hasError();
    /**
     * <code>optional uint32 error = 3;</code>
     */
    int getError();

    // optional string name = 4;
    /**
     * <code>optional string name = 4;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 4;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required .com.zyd.common.proto.client.RPCQueueIDEnum queueId = 5;
    /**
     * <code>required .com.zyd.common.proto.client.RPCQueueIDEnum queueId = 5;</code>
     */
    boolean hasQueueId();
    /**
     * <code>required .com.zyd.common.proto.client.RPCQueueIDEnum queueId = 5;</code>
     */
    com.zyd.common.proto.client.RpcProtocol.RPCQueueIDEnum getQueueId();

    // optional string requestToken = 6;
    /**
     * <code>optional string requestToken = 6;</code>
     */
    boolean hasRequestToken();
    /**
     * <code>optional string requestToken = 6;</code>
     */
    java.lang.String getRequestToken();
    /**
     * <code>optional string requestToken = 6;</code>
     */
    com.google.protobuf.ByteString
        getRequestTokenBytes();
  }
  /**
   * Protobuf type {@code com.zyd.common.proto.client.RpcHeader}
   */
  public static final class RpcHeader extends
      com.google.protobuf.GeneratedMessage
      implements RpcHeaderOrBuilder {
    // Use RpcHeader.newBuilder() to construct.
    private RpcHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcHeader defaultInstance;
    public static RpcHeader getDefaultInstance() {
      return defaultInstance;
    }

    public RpcHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.zyd.common.proto.client.RpcProtocol.RpcType value = com.zyd.common.proto.client.RpcProtocol.RpcType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              error_ = input.readUInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              name_ = input.readBytes();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.zyd.common.proto.client.RpcProtocol.RPCQueueIDEnum value = com.zyd.common.proto.client.RpcProtocol.RPCQueueIDEnum.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                queueId_ = value;
              }
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              requestToken_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_RpcHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_RpcHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zyd.common.proto.client.RpcProtocol.RpcHeader.class, com.zyd.common.proto.client.RpcProtocol.RpcHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcHeader> PARSER =
        new com.google.protobuf.AbstractParser<RpcHeader>() {
      public RpcHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.zyd.common.proto.client.RpcType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.zyd.common.proto.client.RpcProtocol.RpcType type_;
    /**
     * <code>required .com.zyd.common.proto.client.RpcType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.zyd.common.proto.client.RpcType type = 1;</code>
     */
    public com.zyd.common.proto.client.RpcProtocol.RpcType getType() {
      return type_;
    }

    // required uint32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required uint32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    // optional uint32 error = 3;
    public static final int ERROR_FIELD_NUMBER = 3;
    private int error_;
    /**
     * <code>optional uint32 error = 3;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 error = 3;</code>
     */
    public int getError() {
      return error_;
    }

    // optional string name = 4;
    public static final int NAME_FIELD_NUMBER = 4;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 4;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string name = 4;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .com.zyd.common.proto.client.RPCQueueIDEnum queueId = 5;
    public static final int QUEUEID_FIELD_NUMBER = 5;
    private com.zyd.common.proto.client.RpcProtocol.RPCQueueIDEnum queueId_;
    /**
     * <code>required .com.zyd.common.proto.client.RPCQueueIDEnum queueId = 5;</code>
     */
    public boolean hasQueueId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .com.zyd.common.proto.client.RPCQueueIDEnum queueId = 5;</code>
     */
    public com.zyd.common.proto.client.RpcProtocol.RPCQueueIDEnum getQueueId() {
      return queueId_;
    }

    // optional string requestToken = 6;
    public static final int REQUESTTOKEN_FIELD_NUMBER = 6;
    private java.lang.Object requestToken_;
    /**
     * <code>optional string requestToken = 6;</code>
     */
    public boolean hasRequestToken() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string requestToken = 6;</code>
     */
    public java.lang.String getRequestToken() {
      java.lang.Object ref = requestToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestToken_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string requestToken = 6;</code>
     */
    public com.google.protobuf.ByteString
        getRequestTokenBytes() {
      java.lang.Object ref = requestToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = com.zyd.common.proto.client.RpcProtocol.RpcType.RPC_REQUEST;
      id_ = 0;
      error_ = 0;
      name_ = "";
      queueId_ = com.zyd.common.proto.client.RpcProtocol.RPCQueueIDEnum.LOGIN_QUEUE;
      requestToken_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQueueId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, error_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, queueId_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getRequestTokenBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, error_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, queueId_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getRequestTokenBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zyd.common.proto.client.RpcProtocol.RpcHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zyd.common.proto.client.RpcProtocol.RpcHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zyd.common.proto.client.RpcProtocol.RpcHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zyd.common.proto.client.RpcProtocol.RpcHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zyd.common.proto.client.RpcProtocol.RpcHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zyd.common.proto.client.RpcProtocol.RpcHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zyd.common.proto.client.RpcProtocol.RpcHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zyd.common.proto.client.RpcProtocol.RpcHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zyd.common.proto.client.RpcProtocol.RpcHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zyd.common.proto.client.RpcProtocol.RpcHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zyd.common.proto.client.RpcProtocol.RpcHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zyd.common.proto.client.RpcHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zyd.common.proto.client.RpcProtocol.RpcHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_RpcHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_RpcHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zyd.common.proto.client.RpcProtocol.RpcHeader.class, com.zyd.common.proto.client.RpcProtocol.RpcHeader.Builder.class);
      }

      // Construct using com.zyd.common.proto.client.RpcProtocol.RpcHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.zyd.common.proto.client.RpcProtocol.RpcType.RPC_REQUEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        error_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        queueId_ = com.zyd.common.proto.client.RpcProtocol.RPCQueueIDEnum.LOGIN_QUEUE;
        bitField0_ = (bitField0_ & ~0x00000010);
        requestToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_RpcHeader_descriptor;
      }

      public com.zyd.common.proto.client.RpcProtocol.RpcHeader getDefaultInstanceForType() {
        return com.zyd.common.proto.client.RpcProtocol.RpcHeader.getDefaultInstance();
      }

      public com.zyd.common.proto.client.RpcProtocol.RpcHeader build() {
        com.zyd.common.proto.client.RpcProtocol.RpcHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zyd.common.proto.client.RpcProtocol.RpcHeader buildPartial() {
        com.zyd.common.proto.client.RpcProtocol.RpcHeader result = new com.zyd.common.proto.client.RpcProtocol.RpcHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.queueId_ = queueId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.requestToken_ = requestToken_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zyd.common.proto.client.RpcProtocol.RpcHeader) {
          return mergeFrom((com.zyd.common.proto.client.RpcProtocol.RpcHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zyd.common.proto.client.RpcProtocol.RpcHeader other) {
        if (other == com.zyd.common.proto.client.RpcProtocol.RpcHeader.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasError()) {
          setError(other.getError());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000008;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasQueueId()) {
          setQueueId(other.getQueueId());
        }
        if (other.hasRequestToken()) {
          bitField0_ |= 0x00000020;
          requestToken_ = other.requestToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasQueueId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zyd.common.proto.client.RpcProtocol.RpcHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zyd.common.proto.client.RpcProtocol.RpcHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.zyd.common.proto.client.RpcType type = 1;
      private com.zyd.common.proto.client.RpcProtocol.RpcType type_ = com.zyd.common.proto.client.RpcProtocol.RpcType.RPC_REQUEST;
      /**
       * <code>required .com.zyd.common.proto.client.RpcType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.zyd.common.proto.client.RpcType type = 1;</code>
       */
      public com.zyd.common.proto.client.RpcProtocol.RpcType getType() {
        return type_;
      }
      /**
       * <code>required .com.zyd.common.proto.client.RpcType type = 1;</code>
       */
      public Builder setType(com.zyd.common.proto.client.RpcProtocol.RpcType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.zyd.common.proto.client.RpcType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.zyd.common.proto.client.RpcProtocol.RpcType.RPC_REQUEST;
        onChanged();
        return this;
      }

      // required uint32 id = 2;
      private int id_ ;
      /**
       * <code>required uint32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 error = 3;
      private int error_ ;
      /**
       * <code>optional uint32 error = 3;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 error = 3;</code>
       */
      public int getError() {
        return error_;
      }
      /**
       * <code>optional uint32 error = 3;</code>
       */
      public Builder setError(int value) {
        bitField0_ |= 0x00000004;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 error = 3;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000004);
        error_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 4;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 4;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }

      // required .com.zyd.common.proto.client.RPCQueueIDEnum queueId = 5;
      private com.zyd.common.proto.client.RpcProtocol.RPCQueueIDEnum queueId_ = com.zyd.common.proto.client.RpcProtocol.RPCQueueIDEnum.LOGIN_QUEUE;
      /**
       * <code>required .com.zyd.common.proto.client.RPCQueueIDEnum queueId = 5;</code>
       */
      public boolean hasQueueId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .com.zyd.common.proto.client.RPCQueueIDEnum queueId = 5;</code>
       */
      public com.zyd.common.proto.client.RpcProtocol.RPCQueueIDEnum getQueueId() {
        return queueId_;
      }
      /**
       * <code>required .com.zyd.common.proto.client.RPCQueueIDEnum queueId = 5;</code>
       */
      public Builder setQueueId(com.zyd.common.proto.client.RpcProtocol.RPCQueueIDEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        queueId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.zyd.common.proto.client.RPCQueueIDEnum queueId = 5;</code>
       */
      public Builder clearQueueId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        queueId_ = com.zyd.common.proto.client.RpcProtocol.RPCQueueIDEnum.LOGIN_QUEUE;
        onChanged();
        return this;
      }

      // optional string requestToken = 6;
      private java.lang.Object requestToken_ = "";
      /**
       * <code>optional string requestToken = 6;</code>
       */
      public boolean hasRequestToken() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string requestToken = 6;</code>
       */
      public java.lang.String getRequestToken() {
        java.lang.Object ref = requestToken_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requestToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestToken = 6;</code>
       */
      public com.google.protobuf.ByteString
          getRequestTokenBytes() {
        java.lang.Object ref = requestToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestToken = 6;</code>
       */
      public Builder setRequestToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        requestToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestToken = 6;</code>
       */
      public Builder clearRequestToken() {
        bitField0_ = (bitField0_ & ~0x00000020);
        requestToken_ = getDefaultInstance().getRequestToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestToken = 6;</code>
       */
      public Builder setRequestTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        requestToken_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zyd.common.proto.client.RpcHeader)
    }

    static {
      defaultInstance = new RpcHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zyd.common.proto.client.RpcHeader)
  }

  public interface PushHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string userToken = 1;
    /**
     * <code>repeated string userToken = 1;</code>
     */
    java.util.List<java.lang.String>
    getUserTokenList();
    /**
     * <code>repeated string userToken = 1;</code>
     */
    int getUserTokenCount();
    /**
     * <code>repeated string userToken = 1;</code>
     */
    java.lang.String getUserToken(int index);
    /**
     * <code>repeated string userToken = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserTokenBytes(int index);
  }
  /**
   * Protobuf type {@code com.zyd.common.proto.client.PushHeader}
   */
  public static final class PushHeader extends
      com.google.protobuf.GeneratedMessage
      implements PushHeaderOrBuilder {
    // Use PushHeader.newBuilder() to construct.
    private PushHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PushHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PushHeader defaultInstance;
    public static PushHeader getDefaultInstance() {
      return defaultInstance;
    }

    public PushHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PushHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                userToken_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              userToken_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          userToken_ = new com.google.protobuf.UnmodifiableLazyStringList(userToken_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_PushHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_PushHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zyd.common.proto.client.RpcProtocol.PushHeader.class, com.zyd.common.proto.client.RpcProtocol.PushHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<PushHeader> PARSER =
        new com.google.protobuf.AbstractParser<PushHeader>() {
      public PushHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PushHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PushHeader> getParserForType() {
      return PARSER;
    }

    // repeated string userToken = 1;
    public static final int USERTOKEN_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList userToken_;
    /**
     * <code>repeated string userToken = 1;</code>
     */
    public java.util.List<java.lang.String>
        getUserTokenList() {
      return userToken_;
    }
    /**
     * <code>repeated string userToken = 1;</code>
     */
    public int getUserTokenCount() {
      return userToken_.size();
    }
    /**
     * <code>repeated string userToken = 1;</code>
     */
    public java.lang.String getUserToken(int index) {
      return userToken_.get(index);
    }
    /**
     * <code>repeated string userToken = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserTokenBytes(int index) {
      return userToken_.getByteString(index);
    }

    private void initFields() {
      userToken_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < userToken_.size(); i++) {
        output.writeBytes(1, userToken_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < userToken_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(userToken_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getUserTokenList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zyd.common.proto.client.RpcProtocol.PushHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zyd.common.proto.client.RpcProtocol.PushHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zyd.common.proto.client.RpcProtocol.PushHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zyd.common.proto.client.RpcProtocol.PushHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zyd.common.proto.client.RpcProtocol.PushHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zyd.common.proto.client.RpcProtocol.PushHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zyd.common.proto.client.RpcProtocol.PushHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zyd.common.proto.client.RpcProtocol.PushHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zyd.common.proto.client.RpcProtocol.PushHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zyd.common.proto.client.RpcProtocol.PushHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zyd.common.proto.client.RpcProtocol.PushHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zyd.common.proto.client.PushHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zyd.common.proto.client.RpcProtocol.PushHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_PushHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_PushHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zyd.common.proto.client.RpcProtocol.PushHeader.class, com.zyd.common.proto.client.RpcProtocol.PushHeader.Builder.class);
      }

      // Construct using com.zyd.common.proto.client.RpcProtocol.PushHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userToken_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_PushHeader_descriptor;
      }

      public com.zyd.common.proto.client.RpcProtocol.PushHeader getDefaultInstanceForType() {
        return com.zyd.common.proto.client.RpcProtocol.PushHeader.getDefaultInstance();
      }

      public com.zyd.common.proto.client.RpcProtocol.PushHeader build() {
        com.zyd.common.proto.client.RpcProtocol.PushHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zyd.common.proto.client.RpcProtocol.PushHeader buildPartial() {
        com.zyd.common.proto.client.RpcProtocol.PushHeader result = new com.zyd.common.proto.client.RpcProtocol.PushHeader(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          userToken_ = new com.google.protobuf.UnmodifiableLazyStringList(
              userToken_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.userToken_ = userToken_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zyd.common.proto.client.RpcProtocol.PushHeader) {
          return mergeFrom((com.zyd.common.proto.client.RpcProtocol.PushHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zyd.common.proto.client.RpcProtocol.PushHeader other) {
        if (other == com.zyd.common.proto.client.RpcProtocol.PushHeader.getDefaultInstance()) return this;
        if (!other.userToken_.isEmpty()) {
          if (userToken_.isEmpty()) {
            userToken_ = other.userToken_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserTokenIsMutable();
            userToken_.addAll(other.userToken_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zyd.common.proto.client.RpcProtocol.PushHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zyd.common.proto.client.RpcProtocol.PushHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string userToken = 1;
      private com.google.protobuf.LazyStringList userToken_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUserTokenIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          userToken_ = new com.google.protobuf.LazyStringArrayList(userToken_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string userToken = 1;</code>
       */
      public java.util.List<java.lang.String>
          getUserTokenList() {
        return java.util.Collections.unmodifiableList(userToken_);
      }
      /**
       * <code>repeated string userToken = 1;</code>
       */
      public int getUserTokenCount() {
        return userToken_.size();
      }
      /**
       * <code>repeated string userToken = 1;</code>
       */
      public java.lang.String getUserToken(int index) {
        return userToken_.get(index);
      }
      /**
       * <code>repeated string userToken = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserTokenBytes(int index) {
        return userToken_.getByteString(index);
      }
      /**
       * <code>repeated string userToken = 1;</code>
       */
      public Builder setUserToken(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserTokenIsMutable();
        userToken_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userToken = 1;</code>
       */
      public Builder addUserToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserTokenIsMutable();
        userToken_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userToken = 1;</code>
       */
      public Builder addAllUserToken(
          java.lang.Iterable<java.lang.String> values) {
        ensureUserTokenIsMutable();
        super.addAll(values, userToken_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userToken = 1;</code>
       */
      public Builder clearUserToken() {
        userToken_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userToken = 1;</code>
       */
      public Builder addUserTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserTokenIsMutable();
        userToken_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zyd.common.proto.client.PushHeader)
    }

    static {
      defaultInstance = new PushHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zyd.common.proto.client.PushHeader)
  }

  public interface ChatPushHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string suid = 1;
    /**
     * <code>repeated string suid = 1;</code>
     */
    java.util.List<java.lang.String>
    getSuidList();
    /**
     * <code>repeated string suid = 1;</code>
     */
    int getSuidCount();
    /**
     * <code>repeated string suid = 1;</code>
     */
    java.lang.String getSuid(int index);
    /**
     * <code>repeated string suid = 1;</code>
     */
    com.google.protobuf.ByteString
        getSuidBytes(int index);
  }
  /**
   * Protobuf type {@code com.zyd.common.proto.client.ChatPushHeader}
   */
  public static final class ChatPushHeader extends
      com.google.protobuf.GeneratedMessage
      implements ChatPushHeaderOrBuilder {
    // Use ChatPushHeader.newBuilder() to construct.
    private ChatPushHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChatPushHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChatPushHeader defaultInstance;
    public static ChatPushHeader getDefaultInstance() {
      return defaultInstance;
    }

    public ChatPushHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChatPushHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                suid_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              suid_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          suid_ = new com.google.protobuf.UnmodifiableLazyStringList(suid_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_ChatPushHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_ChatPushHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zyd.common.proto.client.RpcProtocol.ChatPushHeader.class, com.zyd.common.proto.client.RpcProtocol.ChatPushHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<ChatPushHeader> PARSER =
        new com.google.protobuf.AbstractParser<ChatPushHeader>() {
      public ChatPushHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatPushHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChatPushHeader> getParserForType() {
      return PARSER;
    }

    // repeated string suid = 1;
    public static final int SUID_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList suid_;
    /**
     * <code>repeated string suid = 1;</code>
     */
    public java.util.List<java.lang.String>
        getSuidList() {
      return suid_;
    }
    /**
     * <code>repeated string suid = 1;</code>
     */
    public int getSuidCount() {
      return suid_.size();
    }
    /**
     * <code>repeated string suid = 1;</code>
     */
    public java.lang.String getSuid(int index) {
      return suid_.get(index);
    }
    /**
     * <code>repeated string suid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSuidBytes(int index) {
      return suid_.getByteString(index);
    }

    private void initFields() {
      suid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < suid_.size(); i++) {
        output.writeBytes(1, suid_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < suid_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(suid_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getSuidList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zyd.common.proto.client.RpcProtocol.ChatPushHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zyd.common.proto.client.RpcProtocol.ChatPushHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zyd.common.proto.client.RpcProtocol.ChatPushHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zyd.common.proto.client.RpcProtocol.ChatPushHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zyd.common.proto.client.RpcProtocol.ChatPushHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zyd.common.proto.client.RpcProtocol.ChatPushHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zyd.common.proto.client.RpcProtocol.ChatPushHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zyd.common.proto.client.RpcProtocol.ChatPushHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zyd.common.proto.client.RpcProtocol.ChatPushHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zyd.common.proto.client.RpcProtocol.ChatPushHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zyd.common.proto.client.RpcProtocol.ChatPushHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zyd.common.proto.client.ChatPushHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zyd.common.proto.client.RpcProtocol.ChatPushHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_ChatPushHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_ChatPushHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zyd.common.proto.client.RpcProtocol.ChatPushHeader.class, com.zyd.common.proto.client.RpcProtocol.ChatPushHeader.Builder.class);
      }

      // Construct using com.zyd.common.proto.client.RpcProtocol.ChatPushHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        suid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zyd.common.proto.client.RpcProtocol.internal_static_com_zyd_common_proto_client_ChatPushHeader_descriptor;
      }

      public com.zyd.common.proto.client.RpcProtocol.ChatPushHeader getDefaultInstanceForType() {
        return com.zyd.common.proto.client.RpcProtocol.ChatPushHeader.getDefaultInstance();
      }

      public com.zyd.common.proto.client.RpcProtocol.ChatPushHeader build() {
        com.zyd.common.proto.client.RpcProtocol.ChatPushHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zyd.common.proto.client.RpcProtocol.ChatPushHeader buildPartial() {
        com.zyd.common.proto.client.RpcProtocol.ChatPushHeader result = new com.zyd.common.proto.client.RpcProtocol.ChatPushHeader(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          suid_ = new com.google.protobuf.UnmodifiableLazyStringList(
              suid_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.suid_ = suid_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zyd.common.proto.client.RpcProtocol.ChatPushHeader) {
          return mergeFrom((com.zyd.common.proto.client.RpcProtocol.ChatPushHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zyd.common.proto.client.RpcProtocol.ChatPushHeader other) {
        if (other == com.zyd.common.proto.client.RpcProtocol.ChatPushHeader.getDefaultInstance()) return this;
        if (!other.suid_.isEmpty()) {
          if (suid_.isEmpty()) {
            suid_ = other.suid_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSuidIsMutable();
            suid_.addAll(other.suid_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zyd.common.proto.client.RpcProtocol.ChatPushHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zyd.common.proto.client.RpcProtocol.ChatPushHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string suid = 1;
      private com.google.protobuf.LazyStringList suid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSuidIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          suid_ = new com.google.protobuf.LazyStringArrayList(suid_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string suid = 1;</code>
       */
      public java.util.List<java.lang.String>
          getSuidList() {
        return java.util.Collections.unmodifiableList(suid_);
      }
      /**
       * <code>repeated string suid = 1;</code>
       */
      public int getSuidCount() {
        return suid_.size();
      }
      /**
       * <code>repeated string suid = 1;</code>
       */
      public java.lang.String getSuid(int index) {
        return suid_.get(index);
      }
      /**
       * <code>repeated string suid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSuidBytes(int index) {
        return suid_.getByteString(index);
      }
      /**
       * <code>repeated string suid = 1;</code>
       */
      public Builder setSuid(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSuidIsMutable();
        suid_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string suid = 1;</code>
       */
      public Builder addSuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSuidIsMutable();
        suid_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string suid = 1;</code>
       */
      public Builder addAllSuid(
          java.lang.Iterable<java.lang.String> values) {
        ensureSuidIsMutable();
        super.addAll(values, suid_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string suid = 1;</code>
       */
      public Builder clearSuid() {
        suid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string suid = 1;</code>
       */
      public Builder addSuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSuidIsMutable();
        suid_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zyd.common.proto.client.ChatPushHeader)
    }

    static {
      defaultInstance = new ChatPushHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zyd.common.proto.client.ChatPushHeader)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zyd_common_proto_client_RpcHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zyd_common_proto_client_RpcHeader_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zyd_common_proto_client_PushHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zyd_common_proto_client_PushHeader_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zyd_common_proto_client_ChatPushHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zyd_common_proto_client_ChatPushHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021RpcProtocol.proto\022\033com.zyd.common.prot" +
      "o.client\"\274\001\n\tRpcHeader\0222\n\004type\030\001 \002(\0162$.c" +
      "om.zyd.common.proto.client.RpcType\022\n\n\002id" +
      "\030\002 \002(\r\022\r\n\005error\030\003 \001(\r\022\014\n\004name\030\004 \001(\t\022<\n\007q" +
      "ueueId\030\005 \002(\0162+.com.zyd.common.proto.clie" +
      "nt.RPCQueueIDEnum\022\024\n\014requestToken\030\006 \001(\t\"" +
      "\037\n\nPushHeader\022\021\n\tuserToken\030\001 \003(\t\"\036\n\016Chat" +
      "PushHeader\022\014\n\004suid\030\001 \003(\t*\350\001\n\007RpcType\022\017\n\013" +
      "RPC_REQUEST\020\000\022\020\n\014RPC_RESPONSE\020\001\022\016\n\nRPC_C" +
      "ANCEL\020\002\022\020\n\014RPC_TRANSMIT\020\003\022\037\n\033RPC_TRANSMI",
      "T_RESPONSE_VALUE\020\004\022\026\n\022RPC_PUSH_TO_CLIENT" +
      "\020\005\022\030\n\024RPC_PROXY_BROAD_CAST\020\006\022!\n\035RPC_SERV" +
      "ER_HEART_BEAT_REQUEST\020\007\022\"\n\036RPC_SERVER_HE" +
      "ART_BEAT_RESPONSE\020\010*W\n\016RPCQueueIDEnum\022\017\n" +
      "\013LOGIN_QUEUE\020\001\022\023\n\017ROOM_GAME_QUEUE\020\002\022\017\n\013T" +
      "HIRD_QUEUE\020\003\022\016\n\nMAIN_QUEUE\020\004B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zyd_common_proto_client_RpcHeader_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zyd_common_proto_client_RpcHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zyd_common_proto_client_RpcHeader_descriptor,
              new java.lang.String[] { "Type", "Id", "Error", "Name", "QueueId", "RequestToken", });
          internal_static_com_zyd_common_proto_client_PushHeader_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_zyd_common_proto_client_PushHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zyd_common_proto_client_PushHeader_descriptor,
              new java.lang.String[] { "UserToken", });
          internal_static_com_zyd_common_proto_client_ChatPushHeader_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_zyd_common_proto_client_ChatPushHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zyd_common_proto_client_ChatPushHeader_descriptor,
              new java.lang.String[] { "Suid", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
