#!/usr/bin/env bash

##############################################################################
##
##  gateway  start up script for UN*X
##
##############################################################################

nohup java -Xms${XMSSIZE} -Xmx${XMXSIZE} -XX:MaxPermSize=${MAXPERM} -cp .:lib/common.jar:lib/javassist-3.18.1-GA.jar:lib/msgpack-0.6.8.jar:lib/fluent-logger-0.3.1.jar:lib/commons-lang-2.4.jar:lib/commons-cli-1.2.jar:lib/jcl-over-slf4j-1.7.5.jar:lib/logback-access-1.0.13.jar:lib/logback-classic-1.0.13.jar:lib/logback-core-1.0.13.jar:lib/spring-aop-4.0.0.RELEASE.jar:lib/spring-beans-4.0.0.RELEASE.jar:lib/spring-context-4.0.0.RELEASE.jar:lib/spring-core-4.0.0.RELEASE.jar:lib/spring-expression-4.0.0.RELEASE.jar:lib/protobuf-java-format-1.2.jar:lib/netty-all-4.0.13.Final.jar:lib/protobuf-java-2.5.0.jar:lib/slf4j-api-1.7.5.jar com.nkm.gw.GateWayServer > log/mt.out 2>&1 &